dataset:
  name: "flowers"
  dataset_dir: "..\\dataset\\flowers"
  num_class: 5
  train:
    pattern: "*_train_*.tfrecord"
    count: 3320
    augmentations:
      - random_brightness:
          max_delta: 0.3
      - random_contrast:
          lower: 0.8
          upper: 1.2
      - random_crop:
          min_h_ratio: 0.5
          min_w_ratio: 0.5
      - random_flip_left_right
      - random_hue:
          max_delta: 0.3
  validation:
    pattern: "*_train_*.tfrecord"
    count: 350
  height: 224
  width: 224
  channel: 3
  mul: 2.0
  add: -1.0

model:
  name: "mobilenet"
  alpha: 1.0
  depth_multiplier: 1
  dropout: 0.001

optimizer:
  name: "adam"
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  epsilon: 0.0000001
  amsgrad: false

loss:
  name: "sparse_categorical_cross_entropy"

metrics:
  - name: "sparse_categorical_accuracy"

training:
  batch_size: 1
  epochs: 1
  verbose: 1

validation:
  batch_size: 1
  steps: 16
  freq: 1
  verbose: 1

summary:
  write_graph: true
  write_images: false
  update_freq: 'epoch'
  histogram_freq: 1

save:
  format: "h5"
  dir_path: "out"
  basename: "model"
