dataset:
  dataset_dir: "..\\dataset\\flowers"
  train:
    pattern: "*_train_*.tfrecord"
    batch_size: 100
    augmentations:
      - random_brightness:
          max_delta: 0.3
      - random_contrast:
          lower: 0.8
          upper: 1.2
      - random_crop:
          min_h_ratio: 0.5
          min_w_ratio: 0.5
      - random_flip_left_right
      - random_hue:
          max_delta: 0.3
  validation:
    pattern: "*_train_*.tfrecord"
    batch_size: 100
  height: 224
  width: 224
  channel: 3
  mul: 2.0
  add: -1.0
